"""initial schema

Revision ID: 08c61347b46f
Revises: 
Create Date: 2026-03-05 20:30:17.286741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c61347b46f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('config_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('usage_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_logs_user_id'), 'llm_usage_logs', ['user_id'], unique=False)
    op.create_table('llm_user_configs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('config_data', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_learning_style', sa.String(), nullable=True),
    sa.Column('daily_learning_goal_minutes', sa.Integer(), nullable=True),
    sa.Column('preferred_llm_model', sa.String(), nullable=True),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('oauth_provider_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('ai_insights', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('ai_insights', sa.Column('course_id', sa.String(), nullable=True))
    op.add_column('ai_insights', sa.Column('insight_data', sa.Text(), nullable=True))
    op.add_column('ai_insights', sa.Column('created_at', sa.String(), nullable=True))
    op.alter_column('ai_insights', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ai_insights', 'insight_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'progress'"))
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.drop_column('ai_insights', 'actionable')
    op.drop_column('ai_insights', 'expires_at')
    op.drop_column('ai_insights', 'description')
    op.drop_column('ai_insights', 'supporting_data')
    op.drop_column('ai_insights', 'title')
    op.drop_column('ai_insights', 'ai_model')
    op.drop_column('ai_insights', 'time_frame')
    op.drop_column('ai_insights', 'suggested_actions')
    op.drop_column('ai_insights', 'insight_id')
    op.drop_column('ai_insights', 'generated_at')
    op.drop_column('ai_insights', 'related_concepts')
    op.drop_column('ai_insights', 'priority')
    op.alter_column('assignments', 'assignment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('assignments', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('assignments', 'course_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'milestone_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'roadmap_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'concept',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'assignment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'essay'"))
    op.alter_column('assignments', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'estimated_time_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(2.0)'))
    op.alter_column('assignments', 'difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'intermediate'"))
    op.alter_column('assignments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'not_started'"))
    op.alter_column('assignments', 'submission_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('assignments', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'completed_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assignments', 'generated_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'gpt-4'"))
    op.drop_index(op.f('idx_assignments_course'), table_name='assignments')
    op.drop_index(op.f('idx_assignments_user'), table_name='assignments')
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    op.alter_column('courses', 'course_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('courses', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('courses', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('courses', 'difficulty_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'intermediate'"))
    op.alter_column('courses', 'start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'target_completion_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'actual_completion_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'planning'"))
    op.alter_column('courses', 'progress_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('courses', 'roadmap_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'onboarding_completed',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('courses', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'last_accessed',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('courses', 'generated_by_ai',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('courses', 'ai_model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_courses_user'), table_name='courses')
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'])
    op.alter_column('feature_toggles', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('feature_toggles', 'ai_assignments',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'ai_roadmaps',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'habit_adaptation',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'content_retrieval',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'socratic_enhancement',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'progress_insights',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.add_column('habit_adaptations', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('habit_adaptations', sa.Column('adaptation_data', sa.Text(), nullable=True))
    op.alter_column('habit_adaptations', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('habit_adaptations', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_habit_adaptations_user_id'), 'habit_adaptations', ['user_id'], unique=False)
    op.drop_column('habit_adaptations', 'success_metrics')
    op.drop_column('habit_adaptations', 'adaptation_type')
    op.drop_column('habit_adaptations', 'status')
    op.drop_column('habit_adaptations', 'confidence')
    op.drop_column('habit_adaptations', 'ai_model')
    op.drop_column('habit_adaptations', 'expected_benefit')
    op.drop_column('habit_adaptations', 'reasoning')
    op.drop_column('habit_adaptations', 'current_behavior')
    op.drop_column('habit_adaptations', 'suggested_change')
    op.drop_column('habit_adaptations', 'actual_outcome')
    op.drop_column('habit_adaptations', 'observed_pattern')
    op.drop_column('habit_adaptations', 'adaptation_id')
    op.drop_column('habit_adaptations', 'implementation_steps')
    op.drop_column('habit_adaptations', 'trial_period_days')
    op.drop_column('habit_adaptations', 'user_feedback')
    op.add_column('learner_profiles', sa.Column('profile_data', sa.Text(), nullable=True))
    op.add_column('learner_profiles', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('learner_profiles', sa.Column('updated_at', sa.String(), nullable=True))
    op.alter_column('learner_profiles', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_column('learner_profiles', 'data')
    op.add_column('learning_habits', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('learning_habits', sa.Column('course_id', sa.String(), nullable=True))
    op.add_column('learning_habits', sa.Column('habit_data', sa.Text(), nullable=True))
    op.add_column('learning_habits', sa.Column('created_at', sa.String(), nullable=True))
    op.alter_column('learning_habits', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_learning_habits_user_id'), 'learning_habits', ['user_id'], unique=False)
    op.drop_column('learning_habits', 'habit_id')
    op.drop_column('learning_habits', 'successful_adaptations')
    op.drop_column('learning_habits', 'drop_off_signals')
    op.drop_column('learning_habits', 'preferred_time_of_day')
    op.drop_column('learning_habits', 'last_updated')
    op.drop_column('learning_habits', 'preferred_break_frequency')
    op.drop_column('learning_habits', 'most_productive_days')
    op.drop_column('learning_habits', 'average_session_duration')
    op.drop_column('learning_habits', 'concepts_mastered_per_week')
    op.drop_column('learning_habits', 'average_assignment_completion_time')
    op.drop_column('learning_habits', 'peak_performance_conditions')
    op.drop_column('learning_habits', 'sessions_per_week')
    op.drop_column('learning_habits', 'unsuccessful_adaptations')
    op.alter_column('learning_sessions', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('learning_sessions', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('learning_sessions', 'course_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'end_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'attention_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.8)'))
    op.alter_column('learning_sessions', 'engagement_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('learning_sessions', 'time_of_day',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'morning'"))
    op.alter_column('learning_sessions', 'day_of_week',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Monday'"))
    op.alter_column('learning_sessions', 'device_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'desktop'"))
    op.drop_index(op.f('idx_sessions_user'), table_name='learning_sessions')
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.drop_column('learning_sessions', 'interruptions')
    op.drop_column('learning_sessions', 'completed')
    op.drop_column('learning_sessions', 'mastery_gained')
    op.alter_column('openai_configs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('openai_configs', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('openai_configs', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'gpt-4'"))
    op.alter_column('openai_configs', 'temperature',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.7)'))
    op.alter_column('openai_configs', 'enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('openai_configs', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('openai_configs', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('retrieved_content', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('retrieved_content', sa.Column('course_id', sa.String(), nullable=True))
    op.add_column('retrieved_content', sa.Column('content_data', sa.Text(), nullable=True))
    op.add_column('retrieved_content', sa.Column('created_at', sa.String(), nullable=True))
    op.alter_column('retrieved_content', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_retrieved_content_user_id'), 'retrieved_content', ['user_id'], unique=False)
    op.drop_column('retrieved_content', 'relevance_score')
    op.drop_column('retrieved_content', 'retrieved_at')
    op.drop_column('retrieved_content', 'ai_model')
    op.drop_column('retrieved_content', 'viewed')
    op.drop_column('retrieved_content', 'helpful')
    op.drop_column('retrieved_content', 'recommended_for_expertise')
    op.drop_column('retrieved_content', 'author')
    op.drop_column('retrieved_content', 'complements_concepts')
    op.drop_column('retrieved_content', 'key_topics')
    op.drop_column('retrieved_content', 'content_type')
    op.drop_column('retrieved_content', 'concept')
    op.drop_column('retrieved_content', 'rating')
    op.drop_column('retrieved_content', 'best_consumed_at')
    op.drop_column('retrieved_content', 'key_takeaways')
    op.drop_column('retrieved_content', 'title')
    op.drop_column('retrieved_content', 'estimated_reading_time')
    op.drop_column('retrieved_content', 'difficulty_level')
    op.drop_column('retrieved_content', 'content_id')
    op.drop_column('retrieved_content', 'url')
    op.drop_column('retrieved_content', 'summary')
    op.add_column('roadmaps', sa.Column('key_concepts', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('prerequisites', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('resources', sa.Text(), nullable=True))
    op.alter_column('roadmaps', 'roadmap_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('roadmaps', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('roadmaps', 'course_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('roadmaps', 'total_estimated_hours',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('roadmaps', 'adapted_to_profile',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('roadmaps', 'adapted_to_habits',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('roadmaps', 'difficulty_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'intermediate'"))
    op.alter_column('roadmaps', 'generated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('roadmaps', 'last_updated',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('roadmaps', 'ai_model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'gpt-4'"))
    op.drop_index(op.f('idx_roadmaps_user'), table_name='roadmaps')
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.create_index(op.f('idx_roadmaps_user'), 'roadmaps', ['user_id'], unique=False)
    op.alter_column('roadmaps', 'ai_model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'gpt-4'"))
    op.alter_column('roadmaps', 'last_updated',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roadmaps', 'generated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roadmaps', 'difficulty_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'intermediate'"))
    op.alter_column('roadmaps', 'adapted_to_habits',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('roadmaps', 'adapted_to_profile',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('roadmaps', 'total_estimated_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('roadmaps', 'course_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roadmaps', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('roadmaps', 'roadmap_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('roadmaps', 'resources')
    op.drop_column('roadmaps', 'prerequisites')
    op.drop_column('roadmaps', 'key_concepts')
    op.add_column('retrieved_content', sa.Column('summary', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('retrieved_content', sa.Column('url', sa.TEXT(), nullable=True))
    op.add_column('retrieved_content', sa.Column('content_id', sa.TEXT(), nullable=True))
    op.add_column('retrieved_content', sa.Column('difficulty_level', sa.TEXT(), server_default=sa.text("'intermediate'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('estimated_reading_time', sa.INTEGER(), server_default=sa.text('(15)'), nullable=True))
    op.add_column('retrieved_content', sa.Column('title', sa.TEXT(), nullable=True))
    op.add_column('retrieved_content', sa.Column('key_takeaways', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('best_consumed_at', sa.TEXT(), server_default=sa.text("'beginning'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('rating', sa.INTEGER(), nullable=True))
    op.add_column('retrieved_content', sa.Column('concept', sa.TEXT(), nullable=True))
    op.add_column('retrieved_content', sa.Column('content_type', sa.TEXT(), server_default=sa.text("'article'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('key_topics', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('complements_concepts', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('author', sa.TEXT(), nullable=True))
    op.add_column('retrieved_content', sa.Column('recommended_for_expertise', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('helpful', sa.INTEGER(), nullable=True))
    op.add_column('retrieved_content', sa.Column('viewed', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('retrieved_content', sa.Column('ai_model', sa.TEXT(), server_default=sa.text("'gpt-4'"), nullable=True))
    op.add_column('retrieved_content', sa.Column('retrieved_at', sa.TEXT(), nullable=True))
    op.add_column('retrieved_content', sa.Column('relevance_score', sa.REAL(), server_default=sa.text('(0.8)'), nullable=True))
    op.drop_index(op.f('ix_retrieved_content_user_id'), table_name='retrieved_content')
    op.alter_column('retrieved_content', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('retrieved_content', 'created_at')
    op.drop_column('retrieved_content', 'content_data')
    op.drop_column('retrieved_content', 'course_id')
    op.drop_column('retrieved_content', 'id')
    op.alter_column('openai_configs', 'updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('openai_configs', 'created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('openai_configs', 'enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('openai_configs', 'temperature',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.7)'))
    op.alter_column('openai_configs', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'gpt-4'"))
    op.alter_column('openai_configs', 'api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('openai_configs', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('learning_sessions', sa.Column('mastery_gained', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('learning_sessions', sa.Column('completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('learning_sessions', sa.Column('interruptions', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.create_index(op.f('idx_sessions_user'), 'learning_sessions', ['user_id'], unique=False)
    op.alter_column('learning_sessions', 'device_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'desktop'"))
    op.alter_column('learning_sessions', 'day_of_week',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Monday'"))
    op.alter_column('learning_sessions', 'time_of_day',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'morning'"))
    op.alter_column('learning_sessions', 'engagement_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('learning_sessions', 'attention_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.8)'))
    op.alter_column('learning_sessions', 'end_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'start_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'course_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('learning_sessions', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('learning_sessions', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('learning_habits', sa.Column('unsuccessful_adaptations', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('learning_habits', sa.Column('sessions_per_week', sa.INTEGER(), server_default=sa.text('5'), nullable=True))
    op.add_column('learning_habits', sa.Column('peak_performance_conditions', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('learning_habits', sa.Column('average_assignment_completion_time', sa.REAL(), server_default=sa.text('(3.5)'), nullable=True))
    op.add_column('learning_habits', sa.Column('concepts_mastered_per_week', sa.REAL(), server_default=sa.text('(2.0)'), nullable=True))
    op.add_column('learning_habits', sa.Column('average_session_duration', sa.INTEGER(), server_default=sa.text('(30)'), nullable=True))
    op.add_column('learning_habits', sa.Column('most_productive_days', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('learning_habits', sa.Column('preferred_break_frequency', sa.INTEGER(), server_default=sa.text('(25)'), nullable=True))
    op.add_column('learning_habits', sa.Column('last_updated', sa.TEXT(), nullable=True))
    op.add_column('learning_habits', sa.Column('preferred_time_of_day', sa.TEXT(), server_default=sa.text("'morning'"), nullable=True))
    op.add_column('learning_habits', sa.Column('drop_off_signals', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('learning_habits', sa.Column('successful_adaptations', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('learning_habits', sa.Column('habit_id', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_learning_habits_user_id'), table_name='learning_habits')
    op.alter_column('learning_habits', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('learning_habits', 'created_at')
    op.drop_column('learning_habits', 'habit_data')
    op.drop_column('learning_habits', 'course_id')
    op.drop_column('learning_habits', 'id')
    op.add_column('learner_profiles', sa.Column('data', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.alter_column('learner_profiles', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('learner_profiles', 'updated_at')
    op.drop_column('learner_profiles', 'created_at')
    op.drop_column('learner_profiles', 'profile_data')
    op.add_column('habit_adaptations', sa.Column('user_feedback', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('trial_period_days', sa.INTEGER(), server_default=sa.text('7'), nullable=True))
    op.add_column('habit_adaptations', sa.Column('implementation_steps', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('habit_adaptations', sa.Column('adaptation_id', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('observed_pattern', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('actual_outcome', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('suggested_change', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('current_behavior', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('reasoning', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('expected_benefit', sa.TEXT(), nullable=True))
    op.add_column('habit_adaptations', sa.Column('ai_model', sa.TEXT(), server_default=sa.text("'gpt-4'"), nullable=True))
    op.add_column('habit_adaptations', sa.Column('confidence', sa.REAL(), server_default=sa.text('(0.7)'), nullable=True))
    op.add_column('habit_adaptations', sa.Column('status', sa.TEXT(), server_default=sa.text("'suggested'"), nullable=True))
    op.add_column('habit_adaptations', sa.Column('adaptation_type', sa.TEXT(), server_default=sa.text("'general'"), nullable=True))
    op.add_column('habit_adaptations', sa.Column('success_metrics', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.drop_index(op.f('ix_habit_adaptations_user_id'), table_name='habit_adaptations')
    op.alter_column('habit_adaptations', 'created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('habit_adaptations', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('habit_adaptations', 'adaptation_data')
    op.drop_column('habit_adaptations', 'id')
    op.alter_column('feature_toggles', 'progress_insights',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'socratic_enhancement',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'content_retrieval',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'habit_adaptation',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'ai_roadmaps',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'ai_assignments',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('feature_toggles', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.create_index(op.f('idx_courses_user'), 'courses', ['user_id'], unique=False)
    op.alter_column('courses', 'ai_model_used',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'generated_by_ai',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('courses', 'last_accessed',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'updated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'onboarding_completed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('courses', 'roadmap_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'progress_percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('courses', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'planning'"))
    op.alter_column('courses', 'actual_completion_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'target_completion_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'start_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('courses', 'difficulty_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'intermediate'"))
    op.alter_column('courses', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('courses', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('courses', 'course_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.create_index(op.f('idx_assignments_user'), 'assignments', ['user_id'], unique=False)
    op.create_index(op.f('idx_assignments_course'), 'assignments', ['course_id'], unique=False)
    op.alter_column('assignments', 'generated_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'gpt-4'"))
    op.alter_column('assignments', 'completed_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'created_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('assignments', 'submission_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'not_started'"))
    op.alter_column('assignments', 'difficulty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'intermediate'"))
    op.alter_column('assignments', 'estimated_time_hours',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(2.0)'))
    op.alter_column('assignments', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'assignment_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'essay'"))
    op.alter_column('assignments', 'concept',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'roadmap_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'milestone_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'course_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assignments', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('assignments', 'assignment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('ai_insights', sa.Column('priority', sa.TEXT(), server_default=sa.text("'medium'"), nullable=True))
    op.add_column('ai_insights', sa.Column('related_concepts', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('ai_insights', sa.Column('generated_at', sa.TEXT(), nullable=True))
    op.add_column('ai_insights', sa.Column('insight_id', sa.TEXT(), nullable=True))
    op.add_column('ai_insights', sa.Column('suggested_actions', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('ai_insights', sa.Column('time_frame', sa.TEXT(), server_default=sa.text("'past_week'"), nullable=True))
    op.add_column('ai_insights', sa.Column('ai_model', sa.TEXT(), server_default=sa.text("'gpt-4'"), nullable=True))
    op.add_column('ai_insights', sa.Column('title', sa.TEXT(), nullable=True))
    op.add_column('ai_insights', sa.Column('supporting_data', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('ai_insights', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('ai_insights', sa.Column('expires_at', sa.TEXT(), nullable=True))
    op.add_column('ai_insights', sa.Column('actionable', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.alter_column('ai_insights', 'insight_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'progress'"))
    op.alter_column('ai_insights', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('ai_insights', 'created_at')
    op.drop_column('ai_insights', 'insight_data')
    op.drop_column('ai_insights', 'course_id')
    op.drop_column('ai_insights', 'id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('llm_user_configs')
    op.drop_index(op.f('ix_llm_usage_logs_user_id'), table_name='llm_usage_logs')
    op.drop_table('llm_usage_logs')
    op.drop_table('llm_configs')
    # ### end Alembic commands ###
