/**
 * LearnOS Database Layer
 * SQLite via better-sqlite3 — synchronous, fast, zero-config.
 * Handles connection, schema creation, and provides a shared db instance.
 */
import Database from 'better-sqlite3';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DB_PATH = join(__dirname, '..', 'db', 'learnos.db');
const SCHEMA_PATH = join(__dirname, 'schema.sql');

// Ensure db directory exists
const dbDir = dirname(DB_PATH);
if (!fs.existsSync(dbDir)) fs.mkdirSync(dbDir, { recursive: true });

const db = new Database(DB_PATH);

// Enable WAL mode for better concurrent read performance
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

// Run schema if tables don't exist
function initSchema() {
  const schema = fs.readFileSync(SCHEMA_PATH, 'utf-8');
  db.exec(schema);
}

// LearnOS starts from scratch: no example content is ever seeded. A fresh
// database boots into honest cold-start empty states — the local user is
// created by ensureLocalUser (middleware/auth.js) and everything else is
// earned or generated by the learner.

// Agent registry = app CONFIG, not example content — the 7 agents must exist for
// the Agents page and routing to work even in zero-seed mode. Idempotent, always
// run. status_text is intentionally empty: real per-agent status isn't tracked,
// so we never fabricate a live telemetry string here. is_active reflects which
// agents are actually wired to a code path (CE/Certification has none yet).
function ensureAgentStatus() {
  const AGENTS = [
    ['TU', 'Tutor',         'Teaches concepts, answers questions, explains deeply.', '--agent-tu', 'cap',    1],
    ['PR', 'Profiling',     'Understands you — your goals, pace, background.',        '--agent-pr', 'user',   1],
    ['CR', 'Curriculum',    'Creates personalized roadmaps and learning paths.',     '--agent-cr', 'graph',  1],
    ['AS', 'Assessment',    'Generates quizzes and evaluates mastery.',              '--agent-as', 'check',  1],
    ['RE', 'Research',      'Finds, summarizes, and cites the best resources.',      '--agent-re', 'search', 1],
    ['AN', 'Analytics',     'Tracks progress and surfaces insights.',                '--agent-an', 'chart',  1],
    ['CE', 'Certification', 'Issues verifiable certificates and badges.',            '--agent-ce', 'ribbon', 0],
  ];
  const stmt = db.prepare("INSERT OR IGNORE INTO agent_status (agent_code, display_name, short_desc, color, icon, status_text, is_active) VALUES (?, ?, ?, ?, ?, '', ?)");
  for (const [code, name, desc, color, icon, active] of AGENTS) stmt.run(code, name, desc, color, icon, active);
}

initSchema();

// Migration: add auth columns to existing DBs (silently ignored if already present)
try { db.exec("ALTER TABLE users ADD COLUMN password_hash TEXT"); } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user'"); } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN notifications_seen_at TEXT"); } catch {}
try { db.exec("CREATE TABLE IF NOT EXISTS revoked_tokens (jti TEXT PRIMARY KEY, expires_at TEXT NOT NULL)"); } catch {}

// Community tables must exist before the example seed (which now populates them
// from db/seed.sql) runs.
try {
  db.exec("CREATE TABLE IF NOT EXISTS community_threads (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT, tag TEXT DEFAULT 'question', votes INTEGER DEFAULT 0, replies_count INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')))");
  db.exec("CREATE TABLE IF NOT EXISTS community_replies (id TEXT PRIMARY KEY, thread_id TEXT NOT NULL REFERENCES community_threads(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')))");
  db.exec("CREATE TABLE IF NOT EXISTS community_votes (user_id TEXT NOT NULL REFERENCES users(id), thread_id TEXT NOT NULL REFERENCES community_threads(id) ON DELETE CASCADE, value INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (user_id, thread_id))");
  db.exec("CREATE INDEX IF NOT EXISTS idx_comm_threads_user ON community_threads(user_id)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_comm_replies_thread ON community_replies(thread_id)");
} catch (e) { console.log('Community migration:', e.message); }

// Course syllabus tables must also exist before the seed, which now ships real
// modules + lessons for the catalog courses.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS course_modules (
    id TEXT PRIMARY KEY,
    course_slug TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    order_idx INTEGER DEFAULT 0,
    estimated_minutes INTEGER DEFAULT 45,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec(`CREATE TABLE IF NOT EXISTS module_lessons (
    id TEXT PRIMARY KEY,
    module_id TEXT NOT NULL REFERENCES course_modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    body_md TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT 'reading',
    order_idx INTEGER DEFAULT 0,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  )`);
} catch (e) { console.log('Course module pre-migration:', e.message); }
// Resource lessons carry the external URL directly so the lesson viewer can
// embed videos / render rich resource cards instead of parsing markdown.
try { db.exec("ALTER TABLE module_lessons ADD COLUMN url TEXT"); } catch {}

// ── M1: Coursera-grade content model (docs/MASTERY_SPEC_V2.md §3.1) ──────────
// Coursera puts a time estimate on *every* item ("Video: 8 min", "Quiz: 30 min")
// and separates ungraded practice from graded, attempt-limited assessment. These
// columns make our lessons carry the same metadata so a syllabus can be honest
// about what it costs and what actually counts.
try { db.exec("ALTER TABLE module_lessons ADD COLUMN estimated_minutes INTEGER"); } catch {}
try { db.exec("ALTER TABLE module_lessons ADD COLUMN is_graded INTEGER DEFAULT 0"); } catch {}
try { db.exec("ALTER TABLE module_lessons ADD COLUMN is_optional INTEGER DEFAULT 0"); } catch {}
try { db.exec("ALTER TABLE module_lessons ADD COLUMN pass_threshold REAL"); } catch {}
try { db.exec("ALTER TABLE module_lessons ADD COLUMN max_attempts INTEGER"); } catch {}

// Module objectives become first-class (they only existed on roadmap nodes), so
// every module can state measurable outcomes the way Coursera modules do.
try { db.exec("ALTER TABLE course_modules ADD COLUMN objectives TEXT"); } catch {}

// Course-level framing: what you can DO after, what you need first, skills tracked.
try { db.exec("ALTER TABLE courses ADD COLUMN outcomes TEXT"); } catch {}
try { db.exec("ALTER TABLE courses ADD COLUMN prerequisites TEXT"); } catch {}
try { db.exec("ALTER TABLE courses ADD COLUMN skills TEXT"); } catch {}
try { db.exec("ALTER TABLE courses ADD COLUMN level TEXT"); } catch {}

// Assessment config for assignments: auto-graded programming test cases, the
// pass bar, and how many attempts a learner gets.
try { db.exec("ALTER TABLE assignments ADD COLUMN tests_json TEXT"); } catch {}
try { db.exec("ALTER TABLE assignments ADD COLUMN rubric_json TEXT"); } catch {}
try { db.exec("ALTER TABLE assignments ADD COLUMN pass_threshold REAL"); } catch {}
try { db.exec("ALTER TABLE assignments ADD COLUMN max_attempts INTEGER"); } catch {}

// ── M9: reach — translation (spec §3.9) ─────────────────────────────────────
// Coursera localises a subset of its catalogue because human translation costs
// money per course per language. We generate content, so any course can be
// translated into any language on demand. Translations live ALONGSIDE the
// original — never overwriting it — so a bad translation cannot destroy the
// source of truth.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS translations (
    id TEXT PRIMARY KEY,
    target_type TEXT NOT NULL,     -- 'lesson'
    target_id TEXT NOT NULL,
    language TEXT NOT NULL,
    title TEXT,
    body_md TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(target_type, target_id, language)
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_translations_lookup ON translations(target_type, target_id, language)");
} catch (e) { console.log('translations migration:', e.message); }

// ── M11: pacing & honest credentials (spec §3.8) ────────────────────────────
// Coursera's real moat is employer recognition — a Google or Stanford name on
// the certificate. We have none of that and must never imply we do. What we CAN
// do is make the credential evidential: exactly what was assessed, the scores,
// the dates, and whether the questions themselves were independently checked.
try { db.exec("ALTER TABLE certificates ADD COLUMN evidence_json TEXT"); } catch {}
try { db.exec("ALTER TABLE certificates ADD COLUMN issuer TEXT DEFAULT 'self-attested'"); } catch {}

// A 115-hour course with no weekly plan is where most online learners quietly
// stop. A plan turns "someday" into a target date and an hours-per-week budget.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS learning_plans (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    scope_type TEXT NOT NULL,          -- 'course' | 'roadmap'
    scope_id TEXT NOT NULL,
    target_date TEXT,
    weekly_hours REAL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_learning_plans_user ON learning_plans(user_id, status)");
} catch (e) { console.log('learning_plans migration:', e.message); }

// ── M10: retention (spec §3.7) ──────────────────────────────────────────────
// Passing an assessment once is not mastery. Coursera does not solve this
// either — a certificate records that you could do something in March, not that
// you can do it in September. We track when a node was last practised so
// retention can decay, and link auto-generated review cards back to the item
// that caught the gap.
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN last_practiced_at TEXT"); } catch {}
try { db.exec("ALTER TABLE flashcards ADD COLUMN source_item_id TEXT"); } catch {}
try { db.exec("ALTER TABLE flashcards ADD COLUMN source_module_id TEXT"); } catch {}
try { db.exec("CREATE INDEX IF NOT EXISTS idx_flashcards_source ON flashcards(source_item_id)"); } catch {}

// ── M8: executable labs (spec §3.6) ─────────────────────────────────────────
// Hands-on practice is the most-valued part of a Coursera program and was the
// thing we most obviously faked — our labs were instructions to go do something
// elsewhere. A lab now carries runnable starter code and its own test cases.
try { db.exec("ALTER TABLE module_lessons ADD COLUMN lab_language TEXT"); } catch {}
try { db.exec("ALTER TABLE module_lessons ADD COLUMN starter_code TEXT"); } catch {}
try { db.exec("ALTER TABLE module_lessons ADD COLUMN lab_tests_json TEXT"); } catch {}

// ── M7: factual grounding & accuracy (spec §3.5) ────────────────────────────
// We now generate content at volume, and depth floors measure quantity, not
// truth. A course of 116 confidently-wrong lessons is worse than 6 shallow
// correct ones, and correctness is the one axis where expert-authored material
// decisively beats generated material. Every quiz item therefore carries a
// verification state, and anything disputed or reported is kept out of graded
// assessment until it is resolved.
try { db.exec("ALTER TABLE quiz_items ADD COLUMN verification_status TEXT DEFAULT 'unverified'"); } catch {}
try { db.exec("ALTER TABLE quiz_items ADD COLUMN verification_note TEXT"); } catch {}
try { db.exec("ALTER TABLE quiz_items ADD COLUMN verified_at TEXT"); } catch {}
// Which verified sources a generated lesson was grounded in, so a learner can
// check the claim rather than trusting it.
try { db.exec("ALTER TABLE module_lessons ADD COLUMN sources_json TEXT"); } catch {}

// Learner-reported errors. The person doing the course is the last line of
// defence against a plausible-sounding mistake.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS content_reports (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    target_type TEXT NOT NULL,      -- 'quiz_item' | 'lesson'
    target_id TEXT NOT NULL,
    reason TEXT NOT NULL,           -- 'wrong_answer' | 'factual_error' | 'unclear' | 'dead_link' | 'other'
    detail TEXT,
    status TEXT NOT NULL DEFAULT 'open',   -- open | resolved | dismissed
    created_at TEXT DEFAULT (datetime('now')),
    resolved_at TEXT
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_content_reports_target ON content_reports(target_type, target_id)");
} catch (e) { console.log('content_reports migration:', e.message); }

// ── M4: specialization roadmaps (spec §3.3) ─────────────────────────────────
// A Coursera Specialization sequences 3-6 whole COURSES into one credential.
// Ours must do the same: a roadmap is a pathway from the learner's measured
// starting point (A) to their stated goal (B), whose nodes can be entire courses
// rather than single modules.
try { db.exec("ALTER TABLE roadmaps ADD COLUMN kind TEXT DEFAULT 'course'"); } catch {}
try { db.exec("ALTER TABLE roadmaps ADD COLUMN goal TEXT"); } catch {}
try { db.exec("ALTER TABLE roadmaps ADD COLUMN placement_json TEXT"); } catch {}
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN node_kind TEXT DEFAULT 'module'"); } catch {}
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN skills TEXT"); } catch {}
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN course_topic TEXT"); } catch {}
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN build_status TEXT"); } catch {}

// ── M3: two-tier assessment (spec §3.2) ─────────────────────────────────────
// Coursera separates ungraded practice (unlimited attempts, explanations shown)
// from graded assessment (attempt-limited, pass threshold, counts toward
// progression). quiz_attempts needs to know which it was, which module/lesson it
// belonged to, which attempt number it is, and whether it passed.
try { db.exec("ALTER TABLE quiz_attempts ADD COLUMN module_id TEXT"); } catch {}
try { db.exec("ALTER TABLE quiz_attempts ADD COLUMN lesson_id TEXT"); } catch {}
try { db.exec("ALTER TABLE quiz_attempts ADD COLUMN course_slug TEXT"); } catch {}
try { db.exec("ALTER TABLE quiz_attempts ADD COLUMN mode TEXT DEFAULT 'practice'"); } catch {}
try { db.exec("ALTER TABLE quiz_attempts ADD COLUMN attempt_no INTEGER DEFAULT 1"); } catch {}
try { db.exec("ALTER TABLE quiz_attempts ADD COLUMN passed INTEGER DEFAULT 0"); } catch {}

// Staged course generation is long-running (one LLM call per module), so jobs
// report incremental progress instead of looking hung.
try { db.exec("ALTER TABLE agent_jobs ADD COLUMN progress REAL"); } catch {}
try { db.exec("ALTER TABLE agent_jobs ADD COLUMN progress_msg TEXT"); } catch {}

// Item bank — questions persist per module/skill so retakes aren't identical and
// spaced review can draw from the same pool.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS quiz_items (
    id TEXT PRIMARY KEY,
    course_slug TEXT,
    module_id TEXT,
    lesson_id TEXT,
    node_id TEXT,
    question TEXT NOT NULL,
    choices_json TEXT NOT NULL,
    answer_idx INTEGER NOT NULL,
    explanation TEXT,
    difficulty TEXT DEFAULT 'medium',
    skill TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_quiz_items_module ON quiz_items(module_id)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_quiz_items_course ON quiz_items(course_slug)");
} catch (e) { console.log('quiz_items migration:', e.message); }

// In-lesson retrieval practice — Coursera poses questions mid-lecture and answers
// them in the next video; we attach them to the lesson at a position.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS lesson_checkpoints (
    id TEXT PRIMARY KEY,
    lesson_id TEXT NOT NULL,
    position INTEGER DEFAULT 0,
    question TEXT NOT NULL,
    choices_json TEXT,
    answer_idx INTEGER,
    explanation TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_lesson_checkpoints ON lesson_checkpoints(lesson_id)");
} catch (e) { console.log('lesson_checkpoints migration:', e.message); }

ensureAgentStatus();  // app config — always present

// ── Migration: Streak tracking ───────────────────────────────────────────────
try { db.exec("ALTER TABLE users ADD COLUMN last_activity_date TEXT"); } catch {}

// ── Migration: AI platform layer (Phase 1) ──────────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS agent_runs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    agent_code TEXT,
    model TEXT,
    provider TEXT DEFAULT 'anthropic',
    managed INTEGER DEFAULT 1,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cache_read_tokens INTEGER DEFAULT 0,
    cache_write_tokens INTEGER DEFAULT 0,
    cost_usd REAL DEFAULT 0,
    latency_ms INTEGER DEFAULT 0,
    status TEXT DEFAULT 'ok',
    error TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_agent_runs_user ON agent_runs(user_id, created_at)");
  db.exec(`CREATE TABLE IF NOT EXISTS agent_jobs (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    input_json TEXT,
    status TEXT DEFAULT 'queued',
    result_json TEXT,
    error TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_agent_jobs_status ON agent_jobs(status, created_at)");
  db.exec(`CREATE TABLE IF NOT EXISTS usage_counters (
    user_id TEXT NOT NULL,
    period TEXT NOT NULL,
    tokens INTEGER DEFAULT 0,
    cost_usd REAL DEFAULT 0,
    requests INTEGER DEFAULT 0,
    PRIMARY KEY (user_id, period)
  )`);
} catch (e) { console.log('AI platform migration:', e.message); }

// ── Migration: Phase 2 — profiles & curriculum ──────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS user_profiles (
    user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    goal TEXT,
    background TEXT,
    level TEXT DEFAULT 'beginner',
    time_per_week INTEGER DEFAULT 5,
    learning_style TEXT,
    motivations TEXT DEFAULT '[]',
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec(`CREATE TABLE IF NOT EXISTS node_objectives (
    id TEXT PRIMARY KEY,
    node_id TEXT NOT NULL,
    roadmap_id TEXT,
    text TEXT NOT NULL,
    order_idx INTEGER DEFAULT 0
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_node_objectives ON node_objectives(node_id)");
  try { db.exec("ALTER TABLE roadmaps ADD COLUMN course_slug TEXT"); } catch {}
} catch (e) { console.log('Phase 2 migration:', e.message); }

// Clean up roadmaps created by the now-removed fork feature (#3).
try { db.prepare("DELETE FROM roadmaps WHERE id LIKE 'rm-fork-%'").run(); } catch {}

// ── Migration: Community media + references (#23) ────────────────────────────
try {
  try { db.exec("ALTER TABLE community_threads ADD COLUMN image_url TEXT"); } catch {}
  try { db.exec("ALTER TABLE community_threads ADD COLUMN ref_type TEXT"); } catch {} // 'course' | 'roadmap'
  try { db.exec("ALTER TABLE community_threads ADD COLUMN ref_id TEXT"); } catch {}
  try { db.exec("ALTER TABLE community_threads ADD COLUMN ref_label TEXT"); } catch {}
} catch (e) { console.log('Community media migration:', e.message); }

// ── Migration: Richer assignments (#11) ──────────────────────────────────────
// Assignments can be coding projects, homeworks, quizzes, or analyses, each with
// a description and a concrete task checklist.
try {
  try { db.exec("ALTER TABLE assignments ADD COLUMN kind TEXT DEFAULT 'homework'"); } catch {}
  try { db.exec("ALTER TABLE assignments ADD COLUMN description TEXT"); } catch {}
  try { db.exec("ALTER TABLE assignments ADD COLUMN tasks TEXT DEFAULT '[]'"); } catch {}
} catch (e) { console.log('Assignment detail migration:', e.message); }

// ── Migration: node_resources (G2.A) ─────────────────────────────────────────
// External, verified learning content attached to a roadmap node — YT videos,
// articles, papers, docs, repos. RE agent proposes (status='proposed');
// the verifier job confirms reachability and flips to 'verified'.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS node_resources (
    id TEXT PRIMARY KEY,
    node_id TEXT NOT NULL,
    roadmap_id TEXT,
    kind TEXT NOT NULL DEFAULT 'article',
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    source TEXT,
    summary TEXT,
    status TEXT NOT NULL DEFAULT 'proposed',
    verified_at TEXT,
    verified_by TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_node_resources_node ON node_resources(node_id)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_node_resources_status ON node_resources(status)");
} catch (e) { console.log('node_resources migration:', e.message); }

// ── Migration: node_lessons (P10) ────────────────────────────────────────────
// Each node has an optional concept body (Markdown) — the actual lesson text a
// learner reads before opening a tutor session.
try {
  db.exec(`CREATE TABLE IF NOT EXISTS node_lessons (
    node_id TEXT PRIMARY KEY,
    body_md TEXT NOT NULL,
    updated_at TEXT DEFAULT (datetime('now'))
  )`);
} catch (e) { console.log('node_lessons migration:', e.message); }

// ── Migration: Certificate verification (#21) ────────────────────────────────
// Certificates are only "verified" credentials when earned on a LearnOS-verified
// course/roadmap. Unverified completions are kept as records but flagged.
try {
  try { db.exec("ALTER TABLE certificates ADD COLUMN verified INTEGER DEFAULT 1"); } catch {}
  try { db.exec("ALTER TABLE certificates ADD COLUMN course_slug TEXT"); } catch {}
} catch (e) { console.log('Certificate verification migration:', e.message); }

// ── Migration: onboarded_at on user_settings ──────────────────────────────────
try { db.exec("ALTER TABLE user_settings ADD COLUMN onboarded_at TEXT"); } catch {}

// ── Migration: course_modules + module_lessons (§3.2) ─────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS course_modules (
    id TEXT PRIMARY KEY,
    course_slug TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT,
    order_idx INTEGER DEFAULT 0,
    estimated_minutes INTEGER DEFAULT 45,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec(`CREATE TABLE IF NOT EXISTS module_lessons (
    id TEXT PRIMARY KEY,
    module_id TEXT NOT NULL REFERENCES course_modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    body_md TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT 'reading',
    order_idx INTEGER DEFAULT 0,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_course_modules_slug ON course_modules(course_slug)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_module_lessons_mid ON module_lessons(module_id)");
  try { db.exec("ALTER TABLE courses ADD COLUMN migrated_modules INTEGER DEFAULT 0"); } catch {}
  try { db.exec("ALTER TABLE courses ADD COLUMN thumbnail_url TEXT"); } catch {}
} catch (e) { console.log('course_modules migration:', e.message); }

// ── Migration: enrollment_progress (§3.2/3.4) ────────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS enrollment_progress (
    user_id TEXT NOT NULL,
    course_slug TEXT NOT NULL,
    lesson_id TEXT NOT NULL,
    completed_at TEXT DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, course_slug, lesson_id)
  )`);
} catch (e) { console.log('enrollment_progress migration:', e.message); }

// ── Migration: assignment_submissions (§3.5) ──────────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS assignment_submissions (
    id TEXT PRIMARY KEY,
    assignment_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    body_md TEXT NOT NULL,
    submitted_at TEXT DEFAULT (datetime('now')),
    grade INTEGER,
    feedback_md TEXT,
    rubric_json TEXT
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_asgn_sub_user ON assignment_submissions(user_id)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_asgn_sub_aid ON assignment_submissions(assignment_id)");
} catch (e) { console.log('assignment_submissions migration:', e.message); }

// ── Migration: schedule reminder_sent_at (§3.8) ───────────────────────────────
try { db.exec("ALTER TABLE schedule_events ADD COLUMN reminder_sent_at TEXT"); } catch {}

// ── Migration: course verification columns (§3.9) ─────────────────────────────
try { db.exec("ALTER TABLE courses ADD COLUMN verified_by TEXT"); } catch {}
try { db.exec("ALTER TABLE courses ADD COLUMN verified_at TEXT"); } catch {}

// ── Migration: whiteboard_strokes (§3.10) ─────────────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS whiteboard_strokes (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    stroke_json TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_wb_strokes_session ON whiteboard_strokes(session_id)");
} catch (e) { console.log('whiteboard_strokes migration:', e.message); }

// ── Migration: roadmap node editing columns (§3.11) ───────────────────────────
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN last_replanned_at TEXT"); } catch {}
// Quiz attempts — real, scored, persisted quiz results (feeds XP, activity, mastery).
try {
  db.exec(`CREATE TABLE IF NOT EXISTS quiz_attempts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    node_id TEXT,
    title TEXT,
    total INTEGER NOT NULL,
    correct INTEGER NOT NULL,
    score INTEGER NOT NULL,
    questions_json TEXT,
    answers_json TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_quiz_attempts_user ON quiz_attempts(user_id, created_at)");
} catch (e) { console.log('quiz_attempts migration:', e.message); }
// `source` marks AN-inserted remedial nodes. The replan path INSERTed into it
// while the column did not exist, so every re-plan threw (swallowed) and the
// "Suggested by AN" highlight could never appear.
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN source TEXT"); } catch {}
// Links a roadmap node to the course whose module teaches it, so a roadmap can
// be a real course pathway from mastery A→B.
try { db.exec("ALTER TABLE roadmap_nodes ADD COLUMN course_slug TEXT"); } catch {}

// ── Migration: profile customization (§3.12) ──────────────────────────────────
try { db.exec("ALTER TABLE users ADD COLUMN bio TEXT"); } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN avatar_url TEXT"); } catch {}
try { db.exec("ALTER TABLE users ADD COLUMN links_json TEXT"); } catch {}
try { db.exec("ALTER TABLE roadmaps ADD COLUMN is_public INTEGER DEFAULT 0"); } catch {}

// ── Migration: email verification + password reset (§3.13) ────────────────────
try { db.exec("ALTER TABLE users ADD COLUMN email_verified INTEGER DEFAULT 0"); } catch {}
try {
  db.exec(`CREATE TABLE IF NOT EXISTS email_verifications (
    token TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec(`CREATE TABLE IF NOT EXISTS password_resets (
    token TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
} catch (e) { console.log('email/pw-reset migration:', e.message); }

// ── Migration: backfill course_modules from syllabus JSON ─────────────────────
try {
  // Check if syllabus column exists (it may not in older DBs)
  const cols = db.prepare("PRAGMA table_info(courses)").all();
  const hasSyllabus = cols.some(c => c.name === 'syllabus');
  if (!hasSyllabus) {
    db.exec("ALTER TABLE courses ADD COLUMN syllabus TEXT");
  }
  const coursesToMigrate = db.prepare("SELECT slug, syllabus FROM courses WHERE (migrated_modules = 0 OR migrated_modules IS NULL) AND syllabus IS NOT NULL AND syllabus != '' AND syllabus != '[]'").all();
  for (const c of coursesToMigrate) {
    try {
      const syllabus = JSON.parse(c.syllabus);
      if (!Array.isArray(syllabus) || syllabus.length === 0) {
        db.prepare("UPDATE courses SET migrated_modules = 1 WHERE slug = ?").run(c.slug);
        continue;
      }
      const tx = db.transaction(() => {
        syllabus.forEach((mod, mi) => {
          const mid = `cm-${c.slug}-${mi}-${Date.now()}`;
          const modTitle = typeof mod === 'string' ? mod : (mod.title || mod.name || `Module ${mi + 1}`);
          const modSummary = typeof mod === 'object' ? (mod.summary || mod.description || null) : null;
          db.prepare('INSERT OR IGNORE INTO course_modules (id, course_slug, title, summary, order_idx) VALUES (?, ?, ?, ?, ?)')
            .run(mid, c.slug, modTitle, modSummary, mi);
          // Create a default empty lesson per module
          const lid = `ml-${mid}-default`;
          db.prepare("INSERT OR IGNORE INTO module_lessons (id, module_id, title, body_md, kind, order_idx) VALUES (?, ?, ?, '', 'reading', 0)")
            .run(lid, mid, `${modTitle} — Reading`);
        });
        db.prepare("UPDATE courses SET migrated_modules = 1 WHERE slug = ?").run(c.slug);
      });
      tx();
    } catch (e) { console.log('Syllabus backfill error for', c.slug, e.message); }
  }
} catch (e) { console.log('Syllabus backfill migration:', e.message); }

// ── Migration: course_versions ────────────────────────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS course_versions (
    course_slug TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    label TEXT,
    notes_json TEXT DEFAULT '[]',
    created_at TEXT DEFAULT (datetime('now')),
    PRIMARY KEY (course_slug, version)
  )`);
} catch (e) { console.log('course_versions migration:', e.message); }

// ── Migration: mastery_events ─────────────────────────────────────────────────
try {
  db.exec(`CREATE TABLE IF NOT EXISTS mastery_events (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    node_id TEXT NOT NULL,
    roadmap_id TEXT,
    event_type TEXT NOT NULL,
    mastery_before REAL DEFAULT 0,
    mastery_after REAL DEFAULT 0,
    delta REAL DEFAULT 0,
    source TEXT,
    created_at TEXT DEFAULT (datetime('now'))
  )`);
  db.exec("CREATE INDEX IF NOT EXISTS idx_mastery_events_node ON mastery_events(node_id)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_mastery_events_user ON mastery_events(user_id, created_at)");
} catch (e) { console.log('mastery_events migration:', e.message); }

// ── Migration: password_resets used_at ────────────────────────────────────────
try { db.exec("ALTER TABLE password_resets ADD COLUMN used_at TEXT"); } catch {}

// ── XP award helper ──────────────────────────────────────────────────────────
// Called by various routes when user earns XP
db.prepare(`
  UPDATE users SET xp = xp + ?, level = CASE WHEN xp + ? >= xp_to_next THEN level + 1 ELSE level END, xp_to_next = CASE WHEN xp + ? >= xp_to_next THEN xp_to_next + 500 ELSE xp_to_next END, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`).run; // prepared for later use via function below

// Append a row to the personal activity feed (#25 — Feed integration).
// Every meaningful user action funnels through here so the Feed reflects real work.
export function logActivity(userId, { kind, text, sub = null, xp = 0, agent = null }) {
  if (!userId || !kind || !text) return;
  const id = `al-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
  db.prepare('INSERT INTO activity_log (id, user_id, kind, text, sub, xp, agent) VALUES (?, ?, ?, ?, ?, ?, ?)')
    .run(id, userId, kind, text, sub, xp, agent);
  return id;
}

// We export a helper function for awarding XP.
// Pass { silent: true } when the caller already logs a descriptive activity row
// (avoids a duplicate generic "Earned N XP" entry in the feed).
export function awardXP(userId, amount, opts = {}) {
  // Get current user state
  const user = db.prepare('SELECT xp, xp_to_next, level FROM users WHERE id = ?').get(userId);
  if (!user) return;
  let newXP = user.xp + amount;
  let newLevel = user.level;
  let newXPToNext = user.xp_to_next;
  while (newXP >= newXPToNext) {
    newXP -= newXPToNext;
    newLevel++;
    newXPToNext = 500 + (newLevel - 1) * 100; // Scaling XP requirement
  }
  db.prepare('UPDATE users SET xp = ?, level = ?, xp_to_next = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?')
    .run(newXP, newLevel, newXPToNext, userId);
  // Log activity (unless the caller is logging its own descriptive entry)
  if (!opts.silent) {
    logActivity(userId, { kind: 'xp', text: `Earned ${amount} XP`, xp: amount });
  }
}

// ── Streak update helper ─────────────────────────────────────────────────────
export function updateStreak(userId) {
  const user = db.prepare('SELECT streak, best_streak, last_activity_date FROM users WHERE id = ?').get(userId);
  if (!user) return;
  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
  if (user.last_activity_date === today) return; // Already counted today
  let newStreak = (user.last_activity_date === yesterday) ? user.streak + 1 : 1;
  const newBest = Math.max(user.best_streak, newStreak);
  db.prepare('UPDATE users SET streak = ?, best_streak = ?, last_activity_date = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?')
    .run(newStreak, newBest, today, userId);

  // Award streak XP bonus
  if (newStreak > 1) {
    awardXP(userId, newStreak * 5); // 5 XP per streak day
  }

  // Award streak badges
  const badges = db.prepare("SELECT COUNT(*) as c FROM badges WHERE user_id = ? AND label LIKE '%streak%'").get(userId).c;
  if (newStreak === 7 && badges === 0) {
    db.prepare('INSERT INTO badges (id, user_id, label, glyph) VALUES (?, ?, ?, ?)').run(`b-str-${userId}`, userId, '7-day streak', 'flame');
  }
  if (newStreak === 30) {
    const has30 = db.prepare("SELECT COUNT(*) as c FROM badges WHERE user_id = ? AND label = '30-day streak'").get(userId).c;
    if (!has30) db.prepare('INSERT INTO badges (id, user_id, label, glyph) VALUES (?, ?, ?, ?)').run(`b-str30-${userId}`, userId, '30-day streak', 'flame');
  }
}

// Award a badge once per (user, label). Returns true if newly awarded so callers
// can toast/log. Badges were previously seeded-only and never earned.
export function awardBadge(userId, label, glyph = 'star') {
  const has = db.prepare('SELECT 1 FROM badges WHERE user_id = ? AND label = ?').get(userId, label);
  if (has) return false;
  db.prepare('INSERT INTO badges (id, user_id, label, glyph) VALUES (?, ?, ?, ?)')
    .run(`b-${Date.now()}-${Math.random().toString(36).slice(2, 5)}`, userId, label, glyph);
  return true;
}

// ── AI platform: agent-run logging + managed-tier usage metering ─────────────
export function logAgentRun(r) {
  db.prepare(`INSERT INTO agent_runs
    (id, user_id, agent_code, model, provider, managed, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_usd, latency_ms, status, error)
    VALUES (@id, @user_id, @agent_code, @model, @provider, @managed, @input_tokens, @output_tokens, @cache_read_tokens, @cache_write_tokens, @cost_usd, @latency_ms, @status, @error)`)
    .run({
      id: r.id, user_id: r.user_id ?? null, agent_code: r.agent_code ?? null,
      model: r.model ?? null, provider: r.provider ?? 'anthropic', managed: r.managed ?? 1,
      input_tokens: r.input_tokens ?? 0, output_tokens: r.output_tokens ?? 0,
      cache_read_tokens: r.cache_read_tokens ?? 0, cache_write_tokens: r.cache_write_tokens ?? 0,
      cost_usd: r.cost_usd ?? 0, latency_ms: r.latency_ms ?? 0,
      status: r.status ?? 'ok', error: r.error ?? null,
    });
}

export function bumpUsage(userId, tokens, cost) {
  const period = new Date().toISOString().slice(0, 7);
  db.prepare(`INSERT INTO usage_counters (user_id, period, tokens, cost_usd, requests)
    VALUES (?, ?, ?, ?, 1)
    ON CONFLICT(user_id, period) DO UPDATE SET
      tokens = tokens + excluded.tokens,
      cost_usd = cost_usd + excluded.cost_usd,
      requests = requests + 1`)
    .run(userId, period, tokens, cost);
}

export default db;
